- gallery.html
- index.html
#Added instagram icon which is very mandatory in Restro sites. Further i will add links too.
> Added Instagram Icon

- about.html
- contact.html
- gallery.html
- icons.html
- index.html
- services.html
- typography.html
> Added all the provided links

- css/style.css
- index.html
Removed duplicate Instagram icons and added hover effect on Instagram and LinkedIn. (#161)
> Removed Duplicate Instagram icon and added hover effects on icons. (#161)

- css/style.css
email visibility in footer improved
> #49 footer visibility issue Fixed

- css/lightGallery.css
- gallery.html
> Adding search bar on food portion 

- index.html
The trademark was showing the previous year. Updated it to 2023.
Fixed issue: #20 
Please check it out and let me know if any changes are to be made. @Anupkjha2601
> Updated trademark in index.html (#20)

- index.html
Please check the index page scroll to top button.
> Top to scroll button

- index.html
Hey @Anupkjha2601 , This resolves issue#20 
I have updated the trade mark to 2023
> Updated the trademark to 2023

- contact.html
- css/style.css
Contact page updated #197
Before
After Updated
> Contact page updated

- css/style.css
- index.html
This PR contains the modified code of updated alignment of website's headings under the issue:
**Headings' UI Position Improvement #80**
> Updated Alignment of Website's Headings

- index.html
"Discover an amazing dining experience at Food Recipe. Our restaurant is a food lover's haven, offering delicious dishes prepared by talented chefs. Whether it's a romantic dinner or a fun gathering, our cozy atmosphere sets the perfect mood. Enjoy high-quality ingredients, excellent service, and create lasting memories. We pride ourselves on providing good food at affordable prices, with authentic flavors that won't strain your budget. Join us today and treat yourself to a delightful dining experience at Food Recipe!"
I have written this meta description. If you need any changes, you can suggest them.
> Issue No. #306 Missing Meta Description on Website Solved.

- css/style.css
Adding line Height between icons and making into circle form.
> Adding line Height

- .vscode/settings.json
- about.html
- contact.html
- css/style.css
- gallery.html
- icons.html
- index.html
- js/script.js
- services.html
- typography.html
(#43 ) Optimize and Set loader on Home page and also set the same for others pages( please add the labels Gssoc'23) .
> Set loader on each page

- CONTRIBUTING.md
hey @Anupkjha2601 @goodchai0 
I have created the licesnse for your github repo
pls do have a look 
solves #206 
thank you
> Adds contributing.md file

- contributing.md
Here's the screenshot of the want it would look like.
> Added Contributing Guidelines and Instructions

- services.html
#378 
The necessary changes have been made.
Kindly review
Thanks
> Grammar correction 

- css/style.css
- index.html
Reverts Anupkjha2601/food-recipes-website#403
> Revert "Fixed Alignment `Major issue`"

- about.html
- contact.html
- gallery.html
- icons.html
- index.html
- services.html
- signup.html
- typography.html
Fixed:- #332 
I have added the target attribute in the footer and also on the signup page.
can we create more than 1 issue in this repo?
> Added  target attribute in footer socials

- css/style.css
- index.html
Reverts Anupkjha2601/food-recipes-website#265
> Revert "you  can clearly  able to see Opening timings , address ,  recent posts "

- README.md
Hello @Anupkjha2601 ,
I have updated the `README.md` images as per the new alignment of the Website and the font changes occured in GSSOC-23.
Now the readme is looking bit nicer than usual. 
[Screencast from 26-06-23 12:13:29 AM IST.webm](https://github.com/Anupkjha2601/food-recipes-website/assets/121503426/6e2c1c2f-0ca1-4f9d-aa94-3ee742171101)
> README.md Upgraded

- about.html
- contact.html
- gallery.html
- icons.html
- services.html
- typography.html
As you mentioned , the navabr logo for food recepies has been added to all the pages .
> navabr logo added on all the pages

- .github/workflows/ISSUE_TEMPLATE/bug-report.md
- .github/workflows/ISSUE_TEMPLATE/project-request.md
- .github/workflows/ISSUE_TEMPLATE/update-request.md
- .github/workflows/pull_request_template.md
added issue and pull template in workflows , done under gssoc'23 pls review my pr
issue #412 
itll help in merging and keeping track of pr an issues
> added issue and pull template

- css/style.css
- gallery.html
Before:
https://github.com/Anupkjha2601/food-recipes-website/assets/95973644/bf228bf5-5c7f-4c18-b2d7-aa604f4495f8
After:
https://github.com/Anupkjha2601/food-recipes-website/assets/95973644/1e395dbe-5fa6-4dc5-9ffa-6f11fba986ba
Clears issue: #13
> Beautufued gallery

- chatBot/script.js
- chatBot/style.css
- css/style.css
- index.html
Reverts Anupkjha2601/food-recipes-website#423
> Revert "Added `openAI-GPT` in ChatBot"

- css/bootstrap.css
- index.html
https://drive.google.com/file/d/1nis7cE4o5I0s2OzTyxtVi40JM6U-OoJT made the req changess see here
> made the website fine

- css/bootstrap.css
- index.html
Reverts Anupkjha2601/food-recipes-website#407
> Revert "made the website fine"

- contributing.md
close issue #384  
update the contribution.md file
> Upadate Contributing.md file

- css/style.css
> back to top button ui improved and animated with box shadow on hover  #431

- CODE_OF_CONDUCT.md
hi @goodchai0 @Anupkjha2601 
I have added a code of conduct to your github repo.
pls do have a look to it
sorry for the delay 
thank you for understanding !!
issue -> #221
> added Code of conduct

- index.html
issue #508 
Removed the unwanted content form the Homepage of the Website
> Removed the unwanted content form the Homepage of Website

- about.html
- gallery.html
- typography.html
Issue is resolved. You can merge it now. @Anupkjha2601 @Ijaiswalshivam
> Social icons are made visible.

- about.html
- contact.html
- css/style.css
- gallery.html
- icons.html
- index.html
- services.html
- signup.html
- typography.html
You can merge it now. @Anupkjha2601
> 2 search bar issue resolved

- about.html
- contact.html
- gallery.html
- icons.html
- services.html
- typography.html
- This PR is about removing the unwanted sidebar button which can found on all pages on desktop mode.
- It will not found for mobile view, only for desktop view it can be found.
- We removed that component from all pages of food recipes website to clean these types of bugs.
- This PR comes under `level1` change because this is about resolving the Bug that found on Food Recipes Website.
- You can further refer this manual [here](https://cdn.discordapp.com/attachments/1099745008157986889/1112784850131357706/image.png) for more details about adding level labels to PR.
> fix: removed the unwanted sidebar button on all pages 🛠

- gallery.html
Issue is solved. You can merge it now. @Anupkjha2601
> Orientation resolved 

- services.html
**Changes Made**
Added <strong> tag to the footer section in services.html.
Also changed the font color using the style tag. 
**Purpose**
Emphasize important information in the footer.
**Additional Information**
This is my first contribution to the project, so any feedback is appreciated.
This pr addresses the issue #561
> Add Strong Tag to Footer Section and font color change

- contact.html
- css/style.css
- gallery.html
I have improved Footer icons in the Gallery page, and also added hover effect to them.
https://github.com/Anupkjha2601/food-recipes-website/assets/105431748/e56152b3-9c3f-4e4e-85bf-09a4fb671f18
> Fixed footer icons in Gallery page and Contact page

- contact.html
Reverts Anupkjha2601/food-recipes-website#593
> Revert "Removed page repetition and fixed social media icons in contact page."

- about.html
- contact.html
- gallery.html
- icons.html
- index.html
- services.html
- signup.html
- typography.html
> feat: improve seo for all pages on food recipes website 🚀 ✨

- css/style.css
#603 Fixed.
You may merge this edit. @Anupkjha2601
> added top and bottom space in the contact footer

- gallery.html
> search box fixed

- icons.html
Reverts Anupkjha2601/food-recipes-website#606
> Revert "Update icons.html"

- contact.html
- gallery.html
- index.html
@Anupkjha2601 @Ijaiswalshivam now the footer section has been updated, please merge and label it
> update footer section #646

- README.md
> docs: fix broken documentation 📝🛠️ 

- about.html
- contact.html
- css/style.css
- gallery.html
- icons.html
- index.html
- services.html
- typography.html
Changed the following html files by adding class called "day" to the span containing text:
about.html
contact.html
gallery.html
icons.html
index.html
services.html
typography.html
Then defined the color property in styles.css.
Days are now visible.
> minor css changes [Days of week now visible under "Open Timings"] Issue #608

- services.html
> distorted icons fixed

- css/lightGallery.css
- gallery.html
Please watch the below video for a better understanding of the styling
https://www.awesomescreenshot.com/video/19517817?key=64ae03857702d2e80e5fe67412963ce1
> gallery page beautified

- .github/workflows/ISSUE_TEMPLATE/refactor.yml
> feat: add issue template for refactoring codebase ⚒️ ✨ 

- .github/workflows/ISSUE_TEMPLATE/bug-report.yml
> feat: add issue template for bug ⚒️✨ 

- .github/workflows/ISSUE_TEMPLATE/feature_request.yml
> feat: revamp feature request issue template ⚒️✨ 

- about.html
- contact.html
- gallery.html
- icons.html
- index.html
- services.html
- typography.html
Clears #627 
Got rid of any line of code that was commented out and not being used in the codebase to make the codebase look neatre and easier to read and understand.
> Got rid of redundant lines of code in all the files

- contact.html
- css/style.css
> fix: contact page navbar improvement

- index.html
I have added GitHub in the footer section.
Closes #555 
@Anupkjha2601 Please review this.
> Added GitHub link in footer.

- README.md
> feat: add gssoc banner to repository documentation 📝✨ 

- css/style.css
I have added the animation that happens on hovering on the cards in services:
> Added Hover Animation to the Cards in Services

- contact.html
- css/style.css
solves #657 
@Anupkjha2601 conflict resolved
> Footer icons are not visible

- contact.html
Issue solved! #664 
Issue solved in the contact page with reformatting the document by proper lining and also by removing the commented code for more understandability.
> contact page issue solved with reformat document

- css/style.css
- index.html
close issue -> #654 
https://github.com/Anupkjha2601/food-recipes-website/assets/114687502/5e72cc59-0fc5-4bf0-868c-97e2fded5725
> removed bottom scroll bar and gird converted in horizontal

- css/style.css
https://github.com/Anupkjha2601/food-recipes-website/assets/92252895/af87a8c9-a0b0-4f5b-9a2c-70007e444bad
> feat: hover effects for icons with revamping on icons page 🪄✨ 

- contact.html
- css/bootstrap.css
- typography.html
Issue solved! #688 
In this PR, I have added the feature of contextual color and background in the typograhy file.
- Here are the changes:
> feature added of Contextual typography added

- css/flexslider.css
- css/style.css
- index.html
Hey @Anupkjha2601 I have removed bug from the testimonials section. Please review my pr and merge it. Thank you!
- Issue #673 
- Before:-
- After:-
> Removed bug from testimonial section

- icons.html
- services.html
- typography.html
Replaced image format from png to webp.
> Changed images from png to webp

- css/style.css
> menu list revamped

- about.html
- css/style.css
https://www.awesomescreenshot.com/video/19626280?key=d7ac9bc520b30dd33e846a5774d6be9a
Added a container and added some additional border-radius to the button on hovering and some border radius to the image
> About page revamp

- about.html
- css/style.css
Added a container to the section along with a border, beautified the image with hover effects and did the same for button as well.
https://www.awesomescreenshot.com/video/19642661?key=a137418aada9115b3601b5659b1f1445
> Menu part of about page revamped

- .github/workflows/greetings.yml
Added the automation to greet the contributor when they open any pr or submit any new issue for review.
> added greeting workflow

- icons.html
Closes Issue- #709 
In this PR, I have added a new feature of social media icons with necessary css and reusing the present components to reduce the number of line of code.
None
> feat: Added the social media icons feature

- css/style.css
Moved the image to the right side in the homepage and added hover effect to the boxes.
See Above.
> Redesigned the Image in the Homepage and added hover effect to boxes

- gallery.html
> gallery title added

- css/style.css
- services.html
> Hover effect improved by adding padding

- css/style.css
I have added/fixed the hovering animation for the rest of the footer social buttons!
See Above.
> Added/Fixed Footer Social Button Hovering Effects

- contributor.html
- css/contributors.css
- index.html
- js/contributor.js
Fixes issue #745 . If you need to add something else please tell me . I mainly focused on making the contributors list. 
Video : 
https://github.com/Anupkjha2601/food-recipes-website/assets/127319225/e10d0eb8-9b50-4cef-9197-75ef6abf10be
> Added Contributors list

- index.html
Social icons in our chef's section are now visible.
> fixed icons in our chef's section.

- css/style.css
- services.html
> Services section beautified

- css/style.css
#528 
Closes #528 
th e text has been aligned
> text updated

- contributor.html
> favicon fixed

- css/style.css
- css/style2.css
- css/style3.css
Reverts Anupkjha2601/food-recipes-website#793
> Revert "Scroll bar modified and Horizontal scroll removed"

- css/style.css
- css/translate.css
- index.html
Reverts Anupkjha2601/food-recipes-website#781
> Revert "#746 Resolved"

- .github/ISSUE_TEMPLATE/feature_request.yml
Closes: #810 
Corrected the project name in issue template from LinkHub to food-recipes-website
> fix: Corrected the project name in issue template

- contributor.html
> scroll button added

- gallery.html
- index.html
- services.html
#639 
**Pull Request Description:**
This pull request introduces a new feature to the project: **RecipeRover**, a food ordering chatbot that offers users complete support through both voice and text interactions. RecipeRover aims to enhance the user experience by providing personalized assistance and facilitating the process of ordering food while browsing recipes.
**Feature Overview:**
1. **Chat Support:** RecipeRover has been integrated into the project to enable interactive chat support for users. It engages users in conversations, providing real-time assistance related to food ordering, recipe suggestions, dietary preferences, and more.
2. **Voice Interaction:** Leveraging advanced AI voice capabilities, RecipeRover now supports voice interaction in addition to text-based …
> Added  Receipe Bot :Receipe Rover

- css/style.css
- index.html
> Added hover effect to the instagram post

- contact.html
- css/style.css
https://www.awesomescreenshot.com/video/19770142?key=35eed0308a78ded81dfd94e76a58ad52
> contact form wrap

- contributor.html
> contributor navbar added

- css/style.css
- icons.html
> glyphicons hover revamped

- css/style.css
- index.html
Fixed the kind of Broken Navbar as shown in the Issue #777 and add the blur effect!
I removed the horizontal scroll bar as well as it was becoming quite awkward 
See Above!
> Fixed Navbar and Added a Design to it

- services.html
- Highlighted the Services when in the page
- Removed Multiple Duplicate Service Cards
See Above
@Anupkjha2601  Hi! Kindly review this PR.  It was great contributing to this repository! Thanks for having me! :))
> Removed Multiple Cards in Services & Highlighted Services when in the page

- css/contributors.css
- js/contributor.js
#773
Contributor page issue resolved
> Contributor page issue resolved

- about.html
- contact.html
- contributor.html
- gallery.html
- index.html
- services.html
> Gallery page search bar text is conflict to the icon

- css/style.css
- index.html
> Styled main page

- css/style.css
- gallery.html
- Improved the Dish's Card on Gallery Page by adding unique Name and description for enhancing the UI & UX of Gallery Page.
https://github.com/Anupkjha2601/food-recipes-website/assets/92252895/64fd793a-81c2-40a4-a86b-0185af3ef2e0
> feat: enhance gallery cards by adding unique dish names and description ☕✨ 

- icons.html
Solves Issue #756 
In this PR, I have added the copy clipboard in the social media icons.
> Added a Copy clipboard in social-media icons

- about.html
- icons.html
Closes Issue #705 
I founded a bug in the about section. So in this PR, i have removed all the negative values in the about section Food price list.
> Removed negative value from the food price list

- css/style.css
Added box shadow to the contact page
> Added box shadow to the contact page

- css/style.css
Added box shadow and hover effects to the cards on the page.
> Added additional effects like box shadow to the page components

- css/lightGallery.css
Added improved hover effects and box shadow to the cards on the page to make it look more alluring
> Added improved hover and box shadow

- css/style.css
Added box shadow to main page cards to make them more attractive
> Added box shadow to maon page cards

- .github/workflows/greeting.yml
Have added appropriate workflow to greet the user whenever they open a new pr or any new issue
> added github workflow for greerting

- css/style.css
- index.html
Select language button UI is added
> Select button UI added

- css/style.css
- index.html
Reverts Anupkjha2601/food-recipes-website#840
> Revert "Revert "fixed the scroll to top button""
